export const SYNC_MESSAGE_TYPES = {
  REQUEST_BOOTSTRAP: "REQUEST_BOOTSTRAP",
  PUSH_TOOL_CATALOG: "PUSH_TOOL_CATALOG",
  PUSH_CATALOG_SNAPSHOT: "PUSH_CATALOG_SNAPSHOT",
  PUSH_HISTORY_SNAPSHOT: "PUSH_HISTORY_SNAPSHOT",
  UPSERT_HISTORY_ENTRY: "UPSERT_HISTORY_ENTRY",
  ACK_HISTORY_ENTRY: "ACK_HISTORY_ENTRY"
};
